### PR TITLE
rspc completed

### PR DESCRIPTION
**Pull request by Aditya-kumar-vyas**
This Pr is ready to merge.
The below new features are included : 
Implemented view project and staff details for faculty. 
implemented outlay information . 
new dashboard integrated. 
api's for project inventory and project staff details . 
ui for rspc admin

### CODE REVIEW

**Comment by PraneGIT** [comment]
@Aditya-kumar-vyas what is the status of this PR ? Are you done with the change?

**Comment by Aditya-kumar-vyas** [comment]
NO raised just for the sake of it will raise the final PR soon with video illustration and usecase Thanks

**Comment by Aditya-kumar-vyas** [comment]
> @Aditya-kumar-vyas what is the status of this PR ? Are you done with the change?

@PraneGIT now i have updated complete module latest code.

**Comment by Aditya-kumar-vyas** [comment]
all api's are also working only database temporary data is needed to be inserted . which is being done by web team and data team. i have consulted with them.

**Pull request merged**
